server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devsync
    username: devsync_user
    password: password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your-email@gmail.com}
    password: ${MAIL_PASSWORD:your-app-password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # OAuth2 Configuration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
            scope:
              - user:email
              - read:user

jwt:
  secret: ${JWT_SECRET:BSp198wEZsUZSse7d0lq3qLUKrCFcfvdvznxChttsWa6rMpwLrZcRhOFOb55jMT7xmSUK25wfmyRpKnVuSOUBg==}
  expiration: 86400000

firebase:
  config-path: ${FIREBASE_CONFIG_PATH:firebase-service-account.json}

cors:
  allowed-origins: http://localhost:3000,http://localhost:19006,exp://192.168.1.100:8081

# WebSocket Configuration
websocket:
  allowed-origins: "*"
  endpoint: "/ws"
  topic-prefix: "/topic"
  app-prefix: "/app"

# File Upload Configuration
file:
  upload-dir: ${FILE_UPLOAD_DIR:uploads/}
  max-file-size: 10MB
  max-request-size: 10MB

logging:
  level:
    com.devsync: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web.socket: DEBUG